version: '3'

services:

  ros2_object_detection:
    build:
      context: ../
      dockerfile: docker/ros2_object_detection.Dockerfile
    network_mode: host
    runtime: nvidia
    ipc: host
    pid: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: ros2 launch isaac_ros_detectnet isaac_ros_detectnet_staubli.launch.py image_topic:=image camera_info_topic:=camera_info 

  bridge:
    build:
      context: ../
      dockerfile: docker/ros_nitros_bridge.Dockerfile
    network_mode: host
    ipc: host
    pid: host
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: ros2 launch isaac_ros_nitros_bridge_ros2 isaac_ros_image_converter.launch.py ros1_ws_path:=/ros1_ws pub_image_name:=image sub_image_name:=detectnet_processed_image

  image_view:
    build:
      context: ../
      dockerfile: docker/ros1.Dockerfile
    runtime: nvidia
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    command: rosrun rqt_image_view rqt_image_view topic:=/ros1_output_image
  